create schema if not exists srs;


CREATE TABLE SRS.REF_MENU
(
	ID NUMBER(6) NOT NULL,
	LABEL VARCHAR2(200),
	LINK VARCHAR2(300),
	ACTIVE CHAR(1),
	LINK_TARGET VARCHAR2(20),
	LINK_LEVEL INTEGER,
	LINK_ORDER INTEGER,
	PARENT_ID NUMBER(6),
	CONSTRAINT PK_REF_MENU_ID PRIMARY KEY(ID)
);

CREATE TABLE SRS.REF_ROLES
(
	ID NUMBER(6) NOT NULL,
	ROLE_NAME VARCHAR2(256),
	CONSTRAINT PK_REF_ROLES_ID PRIMARY KEY(ID),
	CONSTRAINT UNQ_REF_ROLE_NAME UNIQUE (ROLE_NAME)
);

CREATE TABLE SRS.REF_ROLES_MENU
(
	ROLE_ID NUMBER(6),
	MENU_ID NUMBER(6),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SRS.REF_ROLES(ID),
	CONSTRAINT FK_MENU_ID FOREIGN KEY (MENU_ID) REFERENCES SRS.REF_MENU(ID)
);


