create schema if not exists srs;

CREATE TABLE SRS.EMPLOYEE_DETAILS (
	ID NUMBER(6) NOT NULL GENERATED ALWAYS AS IDENTITY,
	ADDRESS_LINE1 VARCHAR2(256 BYTE),
	ADDRESS_LINE2 VARCHAR2(256 BYTE),
	STREET VARCHAR2(100 BYTE),
	AREA VARCHAR2(100 BYTE),
	CITY VARCHAR2(100 BYTE),
	PROVINCE VARCHAR2(100 BYTE),
	ZIP VARCHAR2(10 BYTE),
	BLOOD_GROUP VARCHAR2(10 BYTE),
	PRIMARY_CONTACT_NUMBER VARCHAR2(20 BYTE),
	EMERGENCY_CONTACT_NUMBER VARCHAR2(20 BYTE),
	EMERGENCY_CONTACT_NAME VARCHAR2(255 BYTE),
	EMERGENCY_CONTACT_RELATION VARCHAR(30 BYTE),
	PRIMARY KEY (ID)
);

CREATE TABLE SRS.EMPLOYEE (
       ID NUMBER(6) NOT NULL GENERATED ALWAYS AS IDENTITY,
        EMAIL_ID VARCHAR2(256 BYTE),
        FIRST_NAME VARCHAR2(256 BYTE),
        LAST_NAME VARCHAR2(256 BYTE),
		EMP_DETAILS_ID NUMBER(6),
        PRIMARY KEY (ID),
		CONSTRAINT FK_EMD_ID FOREIGN KEY(EMP_DETAILS_ID) REFERENCES SRS.EMPLOYEE_DETAILS(ID),
		CONSTRAINT UNQ_EMD_ID UNIQUE (EMP_DETAILS_ID)
);